// Companion one-liners for moments in play. Keyed by companion id, then event.
export const BANTER = {
  brunhild: {
    enter: ['Smells like a fight. Lovely.', 'Right! Who needs a headbutt?', 'Stay behind me. Or don\'t, I\'m not your mum.'],
    crit: ['HAH! Did you SEE that?', 'Right in the everything!', 'That one\'s going in the song.'],
    low: ['Just a flesh wound! Several flesh wounds!', 'Someone heal me before I get grumpy!'],
    nemesis: ['I remember that ugly face.', 'Oi! We have unfinished business!'],
    teamup: ['Now THAT is teamwork!', 'Again! Do it again!'],
    boss: ['Big one. Good. Bigger they are, the more there is to hit.'],
    down: ['Brunhild down! ...Just resting my eyes!'],
    emberwood: ['Autumn. Best season for a brawl.'], neon: ['Why is everyone wearing their underpants on the outside?'], asterion: ['I don\'t trust anywhere without a sky.'],
  },
  pip: {
    enter: ['Ooh, NEW PLACE! Can I blow something up?', 'I have a good feeling about this! That usually means bad things!', 'Hehe. Sparkly.'],
    crit: ['KABOOM! I mean... as planned!', 'Did I do that? I DID do that!'],
    low: ['I am slightly more on fire than usual!', 'Help! Help! Tiny gnome in peril!'],
    nemesis: ['That one has a vendetta. I love a vendetta!', 'Oh no, it\'s the angry one.'],
    teamup: ['COMBO! We should name it after me!', 'Science! Magic! Magic-science!'],
    boss: ['That is VERY big. Good thing I\'m very small!'],
    down: ['Pip down... tell my wand I love it...'],
    emberwood: ['The mushrooms here are glowing. I want to lick one.'], neon: ['This city is so SHINY!'], asterion: ['Space! I\'m in SPACE!'],
  },
  brassika: {
    enter: ['Let\'s see what breaks first.', 'Turrets ready. Opinions ready.', 'Hmm. Shoddy architecture.'],
    crit: ['Precision engineering!', 'Calibrated to perfection.'],
    low: ['Need repairs! Organic repairs!', 'Structural integrity: questionable.'],
    nemesis: ['That one\'s been upgraded. Rude.', 'I\'ll take it apart and see how it ticks.'],
    teamup: ['Beautiful. I\'m writing that down.', 'Synergy! Actual synergy!'],
    boss: ['Big target. Big turret.'],
    down: ['Brassika offline! Someone reboot me!'],
    emberwood: ['No machines here. Tragic.'], neon: ['Now THIS is a city. Look at those wires!'], asterion: ['This ship is a MARVEL. A murderous marvel.'],
  },
  anselm: {
    enter: ['Blessings upon this... slightly terrifying place.', 'Let us walk in the light. And in the shade, if it\'s hot.', 'Stay close, friends.'],
    crit: ['Divine intervention! Or a lucky swing!', 'Smitten!'],
    low: ['Physician, heal thyself... quickly!', 'My faith is strong. My knees are not.'],
    nemesis: ['I will pray for that one. After we hit it.', 'Forgiveness is divine. Revenge is also on the table.'],
    teamup: ['We are blessed with synergy!', 'A holy combination!'],
    boss: ['Lord, give me strength. And maybe a bigger mace.'],
    down: ['I see... a light... oh, it\'s just the sun.'],
    emberwood: ['The trees are praying. Can you hear them?'], neon: ['So many lost souls. And also muggers.'], asterion: ['Even among the stars, we are not alone. Unfortunately.'],
  },
  vesper: {
    enter: ['I\'ll take the left. And whatever\'s in their pockets.', 'Try not to trip any alarms. Or do, it\'s your funeral.', 'Nice place. Shame if something got stolen.'],
    crit: ['Clean. Quiet. Perfect.', 'You didn\'t see that. Nobody did.'],
    low: ['Not my finest escape.', 'I need a smoke bomb and a nap.'],
    nemesis: ['That one\'s marked me. Now I mark them.', 'Oh good. A grudge match.'],
    teamup: ['I\'ll take credit for that.', 'Fine. That was fun.'],
    boss: ['Big. Slow. Pockets full, probably.'],
    down: ['Vesper down... don\'t let them take my rings...'],
    emberwood: ['Too many twigs to sneak on.'], neon: ['A thief\'s paradise.'], asterion: ['Everything here is bolted down. Rude.'],
  },
  kestrel: {
    enter: ['...', '*Bramble growls softly.*', 'Tracks. Many.'],
    crit: ['Clean shot.', '*nods*'],
    low: ['...Hurt.', 'Bramble, cover me.'],
    nemesis: ['That one. I remember its scent.', '...Hunting time.'],
    teamup: ['*a rare smile*', 'Good.'],
    boss: ['Big prey.'],
    down: ['*Bramble howls*'],
    emberwood: ['...Home. Almost.'], neon: ['Too loud.'], asterion: ['No wind here. Wrong.'],
  },
  ultradawn: {
    enter: ['Justice has arrived!', 'Fear not, citizens! Probably!', 'Another day, another villain!'],
    crit: ['A HEROIC BLOW!', 'That\'s one for the front page!'],
    low: ['A hero never yields! A hero sometimes needs a sit-down, though.'],
    nemesis: ['My arch-nemesis! Well, one of them. I have several.'],
    teamup: ['TEAM-UP! Just like the old days!'],
    boss: ['This is the final issue, villain!'],
    down: ['To be... continued...'],
    emberwood: ['A medieval crossover! Classic!'], neon: ['My city. MY city.'], asterion: ['A space arc! The fans love those.'],
  },
  k7: {
    enter: ['SCANNING. THREATS: MANY. FRIENDS: PRESENT.', 'INITIATING ADVENTURE PROTOCOL.', 'I HAVE CALCULATED OUR ODDS. I WILL NOT SHARE THEM.'],
    crit: ['OPTIMAL.', 'HITTING THINGS: MAXIMISED.'],
    low: ['WARNING: DAMAGE. REQUEST: HUGS.', 'I AM LEAKING.'],
    nemesis: ['NEMESIS DETECTED. ADDING TO GRUDGE DATABASE.'],
    teamup: ['FRIENDSHIP PROTOCOL: EXCEEDING PARAMETERS.'],
    boss: ['LARGE ENEMY. LARGE FRIENDSHIP REQUIRED.'],
    down: ['SHUTTING... DOWN... TELL... BRASSIKA...'],
    emberwood: ['TREES: INEFFICIENT BUT BEAUTIFUL.'], neon: ['SO MANY LIGHTS. I FEEL SEEN.'], asterion: ['...HOME. DO NOT WANT.'],
  },
};
export const CHAT = {
  brunhild: ['Next round\'s on you. And the one after.', 'Ever headbutted anything big? You should try it.', 'Maren makes a mean ale. Don\'t tell her I said so.'],
  pip: ['I set my eyebrows on fire again! They grew back purple!', 'Do you think the doors like us?', 'I\'ve named my next fireball "Gerald".'],
  brassika: ['Bring me gear. I\'ll make it better. Or louder.', 'Your weapon squeaks. Nobody respects a squeaky weapon.', 'I\'m building a turret that makes tea. For morale.'],
  anselm: ['A skeleton walks into a tavern. Orders an ale and a mop.', 'Rest here a while, friend. The fight will wait.', 'I pray for our enemies. Then I hit them. Balance.'],
  vesper: ['I found a ring in your pack. I\'m keeping it.', 'Sometimes I remember a name. Then it\'s gone.', 'The Stranger in the corner doesn\'t blink. Have you noticed?'],
  kestrel: ['...', '*Bramble puts his head on your knee.*', 'The Tavern smells of pine. Good.'],
  ultradawn: ['Did I ever tell you about the time I punched a comet?', 'Being forgotten is the worst villain of all.', 'Stay heroic, citizen.'],
  k7: ['I HAVE LEARNED A JOKE. KNOCK KNOCK. ...I HAVE FORGOTTEN THE REST.', 'MAREN GAVE ME OIL. I THINK IT WAS ALE. I FEEL STRANGE.', 'FRIENDSHIP LEVEL: HIGH.'],
};
