// Tavern regulars, companions and realm characters. `look` feeds the voxel model builder.
export const NPCS = {
  maren:    { name: 'Old Maren', title: 'Barkeep of the Hearth Between', color: '#e0a060', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0xe8b890, body: 0x6a3a5a, legs: 0x3a2a3a, accent: 0xe0c070, hair: 0xe8e8f0 }, extras: ['apron'], longHair: true } },
  grizzle:  { name: 'Grizzle', title: 'Merchant of Questionable Goods', color: '#c0a040', idle: 'stand', look: { kind: 'humanoid', bulk: 1.2, colors: { skin: 0x9a7a5a, body: 0x6a4a2a, legs: 0x3a2a1a, accent: 0xe0c040, hat: 0x3a2a1a }, hat: 'tophat', beard: 0x5a4a3a, extras: ['backpack'] } },
  lute:     { name: 'Lute Larkspur', title: 'Bard (Self-Described Legend)', color: '#e06aa0', idle: 'cheer', look: { kind: 'humanoid', colors: { skin: 0xf0c8a0, body: 0xc03a6a, legs: 0x3a2a5a, accent: 0xf0d040, hat: 0x6a2a8a, hair: 0xf0d040 }, hat: 'cap', weapon: 'lute', extras: ['cape'] } },
  carto:    { name: 'Madame Cartographa', title: 'Mapper of Rifts', color: '#6a8ae0', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0x8a6a5a, body: 0x2a3a6a, legs: 0x1a2a4a, accent: 0xc0a040, hair: 0x1a1a1a }, hat: 'wizard', extras: ['robe'], longHair: true } },
  rollo:    { name: 'Rollo Stonecup', title: 'Dice Shark', color: '#a08060', idle: 'sit', look: { kind: 'humanoid', scale: 0.8, bulk: 1.3, colors: { skin: 0xe0a080, body: 0x4a6a3a, legs: 0x3a2a1a, accent: 0xa08040, hair: 0xc04020 }, beard: 0xc04020, hat: 'helm' } },
  stew:     { name: 'Mama Stew', title: 'Cook', color: '#e08040', idle: 'stand', look: { kind: 'humanoid', bulk: 1.3, colors: { skin: 0x7a4a3a, body: 0xe0e0d0, legs: 0x5a4a3a, accent: 0xd03a3a }, hat: 'chef', extras: ['apron'] } },
  ghost:    { name: 'Sir Wispington', title: 'Resident Ghost (Deceased)', color: '#a0e0ff', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0xc0f0ff, body: 0x80c0e0, legs: 0x80c0e0, accent: 0xe0f8ff, eye: 0x2060a0 }, hat: 'helm', weapon: 'sword', glowEyes: 0xa0f0ff } },
  stranger: { name: 'The Hooded Stranger', title: '???', color: '#888', idle: 'sit', look: { kind: 'humanoid', colors: { skin: 0x2a2a2a, body: 0x1a1a1a, legs: 0x111111, accent: 0x3a3a3a, hat: 0x1a1a1a }, hat: 'hood', glowEyes: 0xff3a8a, extras: ['cape'] } },
  // realm NPCs
  elowen:   { name: 'Ranger Elowen', title: 'Warden of Emberwood', color: '#8ab04a', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0xe0c0a0, body: 0x5a7a2a, legs: 0x4a3a2a, accent: 0xc08a3a, hat: 0x3a5a22, hair: 0xc05a2a }, hat: 'hood', weapon: 'bow', extras: ['quiver', 'cape'] } },
  spark:    { name: 'Spark', title: 'Ex-Sidekick, Current Electrician', color: '#ffd23a', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0xc08060, body: 0xffd020, legs: 0x2a2a4a, accent: 0x2a2a4a, hat: 0xffd020 }, hat: 'mask', extras: ['cape', 'emblem'], weapon: 'baton' } },
  pell:     { name: 'Ensign Pell', title: 'Last Crew Member Standing', color: '#40ffd0', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0xe0b090, body: 0xd06a20, legs: 0x5a5a60, accent: 0x40ffd0, hair: 0x2a1a10 }, hat: 'cap', weapon: 'gun' } },
  civilian: { name: 'Frightened Citizen', title: '', color: '#aaa', idle: 'stand', look: { kind: 'humanoid', colors: { skin: 0xe0b090, body: 0x4a8ac0, legs: 0x3a3a3a, accent: 0x2a2a2a, hair: 0x3a2a1a } } },
};

// Companions: recruitable party members. One per class plus two unlockables.
export const COMPANIONS = {
  brunhild: { name: 'Dame Brunhild', classId: 'fighter', title: 'Knight of the Tankard', color: '#d8443a', look: { skin: 0xe8b08a, hair: 0xd8a040 }, beard: null, longHair: true, bio: 'A broad, loud knight who swears she once headbutted a dragon. Nobody can prove otherwise.', unlock: null },
  pip:      { name: 'Pip Fizzlewick', classId: 'sorcerer', title: 'Gnome of Unstable Magic', color: '#b04ae0', look: { skin: 0xf0c8a0, hair: 0x40d0ff }, bio: 'Tiny, excitable and almost always slightly on fire. Treats every Wild Surge as a gift.', unlock: null, scale: 0.8 },
  brassika: { name: 'Brassika Tock', classId: 'artificer', title: 'Tinker of the Tavern Forge', color: '#e0a030', look: { skin: 0x8a5a3a, hair: 0x1a1a1a }, bio: 'Runs the Tavern forge. Has opinions about every weapon you own and will share them.', unlock: null },
  anselm:   { name: 'Brother Anselm', classId: 'cleric', title: 'Healer, Punster', color: '#f0d060', look: { skin: 0xd09a70, hair: 0x5a3a20 }, bio: 'A gentle monk whose only sin is his puns. His faith is unshakable. So are his jokes.', unlock: null },
  vesper:   { name: 'Vesper Nightbloom', classId: 'rogue', title: 'Thief Who Stole Her Own Past', color: '#40c080', look: { skin: 0xc0a0e0, hair: 0x1a1a3a }, longHair: true, bio: 'A sardonic thief who woke in the Tavern with no memory and a pocket full of other people\'s rings.', unlock: null },
  kestrel:  { name: 'Kestrel', classId: 'ranger', title: 'Quiet Hunter (and Bramble)', color: '#6ab04a', look: { skin: 0xa07050, hair: 0x2a1a0a }, bio: 'Speaks rarely. Her wolf Bramble speaks for her, mostly by growling at merchants.', unlock: null },
  ultradawn:{ name: 'Captain Ultra-Dawn', classId: 'fighter', title: 'Retired Superhero', color: '#3a8aff', look: { skin: 0xc08060, body: 0x2a5ad0, legs: 0x2a5ad0, accent: 0xd03a3a, cape: 0xd03a3a, hair: 0xe0e0e0 }, bio: 'The greatest hero Neon Meridian ever forgot. Fights with a shield and a lot of speeches.', unlock: 'neon' },
  k7:       { name: 'Unit K-7', classId: 'artificer', title: 'Stray Maintenance Robot', color: '#40ffd0', look: { skin: 0xa0a8b0, body: 0xd0d8e0, legs: 0x5a6068, accent: 0x40ffd0, hair: null, eye: 0x40ffd0 }, bio: 'A maintenance bot that walked off the Asterion and refused to walk back. Learning "friendship" (it thinks it is a protocol).', unlock: 'asterion' },
};
